# Use Nginx to serve the React build
FROM nginx:alpine

# Copy build folder into Nginx html folder
COPY build/ /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
